### PR TITLE
Move to travis

### LINKED ISSUE #1: Build and deploy ESDoc using Travis CI
Currently, ESDoc is used to provide a website documenting the codebase. We use GitHub Pages to serve this from a directory in the repository. 

This is easy, Pages does a lot of work for us. But we would need to make sure to build and commit the docs before pushing any changes to the repo. A lot of diffs in the commit history would include unneccessary information on the html files in the docs directory. Instead, I suggest making Travis CI watch the repo, building and deploying the docs for us after any change to the codebase.

We could use an inexpensive service such as S3 or Google Cloud Storage to serve these docs, since they're all static anyway.

Looking at the build script in `package.json`, we could use a `.travis.yml` file such as this:

```
sudo: false
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
- rm -r -f docs/
script:
- npm run build:docs
after_success:
- google-cloud-sdk/bin/gsutil -m cp -r -z "html,js,css" docs/** gs://press-js-wp-rest-docs
```

The docs would then be available at [https://storage.googleapis.com/press-js-wp-rest-docs](https://storage.googleapis.com/press-js-wp-rest-docs)

What do you think, @esphen?

### PR DESCRIPTION
**Pull request by thms-rmb**
This should fix #1, by building the docs and deploying to Google Cloud Storage.

@esphen, could you fix the git hook stuff to complete the transition to Travis?

### CODE REVIEW

**Comment by esphen** [comment]
Sure, I'll remove the doc building hook this evening. Remove the doc directory from git too?

**Comment by thms-rmb** [comment]
That's up to you :-) 

Also, the link is live: [https://storage.googleapis.com/press-js-wp-rest-docs/index.html](https://storage.googleapis.com/press-js-wp-rest-docs/index.html)

Sadly, Google Cloud Storage doesn't provide an easy way to serve index.html automatically on requests to `/`, it seems.

**Comment by esphen** [comment]
is it safe to just dump the authentication key into the repo like this? Is ` -K $encrypted_303de93ac7fd_key` only present on travis?

**Comment by thms-rmb** [comment]
Yes, it's the result of doing `travis encrypt-file foo --add`.  I don't really understand the details, but it involves my personal GitHub account (I need to be logged in in order to use this command). The logs for the build hide the actual values in these keys somehow.

More information here: [https://docs.travis-ci.com/user/encrypting-files/](https://docs.travis-ci.com/user/encrypting-files/).

And here: [https://cloud.google.com/solutions/continuous-delivery-with-travis-ci#encryption_and_decryption](https://cloud.google.com/solutions/continuous-delivery-with-travis-ci#encryption_and_decryption)

**Pull request merged**
